import Head from 'next/head'
import FeaturedPost from "../components/FeaturedPost";
import {Post, PostService} from "tnn-sdk";
import {GetServerSideProps} from "next";

interface HomeProps {
    posts: Post.Paginated;
}

export default function Home(props: HomeProps) {
    // const [posts, setPosts] = useState<Post.Paginated>();
    //
    // useEffect(() => {
    //     PostService.getAllPosts({ page: 0 }).then(setPosts);
    // }, []);

    const {posts} = props;
    
    return (
        <div>
            <Head>
                <title>AlgaNews</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {
                posts?.content && <FeaturedPost postSummary={posts?.content[0]} />
            }

        </div>
  )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async (context) => {
    const {page} = context.query;

    const posts = await PostService.getAllPosts({ page: Number(page) - 1 });


    return {
        props: {
            posts
        }
    }
}
